[window]
opacity = 1

[window.padding]
x = 20
y = 5

[font]
size = 10.5

[font.normal]
family = "HackNerdFont"
style = "Regular"

[font.bold]
family = "HackNerdFont"
style = "Bold"

[font.bold_italic]
family = "HackNerdFont"
style = "Bold Italic"

[font.italic]
family = "HackNerdFont"
style = "Italic"

[general]
import = ["~/dotfiles/alacritty/linux_tty.toml"]
