## oama version 0.22.0 - 2025-08-29 0290.e419ef10
## Not all defaults are shown, for full list run `oama printenv`
## and look at the `services:` section.

## Possible options for keeping refresh and access tokens:
## GPG - in a gpg encrypted file $XDG_STATE_HOME/oama/<email-address>.oauth
##       (XDG_STATE_HOME defaults to ~/.local/state)
## GPG - in a gpg encrypted file ~/.local/state/oama/<email-address>.oauth
## KEYRING - in the keyring of a password manager with Secret Service API
##

encryption:
  tag: GPG
  contents: akisarou90@gmail.com

services:
  google:
    client_id_cmd: "pass oauth/gmail/client_id | head -n1"
    client_secret_cmd: "pass oauth/gmail/client_secret | head -n1"
    auth_scope: "https://mail.google.com/ https://www.googleapis.com/auth/calendar"

  microsoft:
    tenant: nablesolutions.com
    auth_endpoint: https://login.microsoftonline.com/nablesolutions.com/oauth2/v2.0/authorize
    token_endpoint: https://login.microsoftonline.com/nablesolutions.com/oauth2/v2.0/token
    device_endpoint: https://login.microsoftonline.com/nablesolutions.com/oauth2/v2.0/devicecode
    client_id_cmd: "pass oauth/microsoft/client_id | head -n1"
    client_secret_cmd: "pass oauth/microsoft/client_secret | head -n1"
